=== mwprezes/XML/zadanie5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com" xmlns="http://www.example.com">
	<xs:complexType name="typTematu">
		<xs:sequence>
			<xs:element name="tematTematu" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="informacja">
		<xs:sequence>
			<xs:element name="temat" type="typTematu"/>
			<xs:element name="podpis" type="xs:string"/>
			<xs:element name="cytat" type="xs:string"/>
		</xs:sequence>
	</xs:group>
	
	<xs:element name="d">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nazwa"/>
				<xs:element ref="miasto"/>
				<xs:element ref="ulica"/>
				<xs:element ref="kod_pocztowy"/>
				<xs:element ref="telefon"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[d]([0-9])*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="gra">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tytuł"/>
				<xs:element ref="twórcy"/>
				<xs:element ref="data_premiery"/>
				<xs:element ref="dystrybutor"/>
				<xs:element ref="cena"/>
				<xs:element ref="rok_produkcji"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[p]([0-9])*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="gatunek" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="kto">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="([a-zA-Z])*"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="cena">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_cena">
					<xs:attribute name="waluta" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="EUR"/>
								<xs:enumeration value="PLN"/>
								<xs:enumeration value="USD"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="data"/>
	<xs:element name="autor">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="3"/>
				<xs:maxLength value="20"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="cytat">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="kto"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nazwa">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="CD Projekt"/>
				<xs:enumeration value="EA"/>
				<xs:enumeration value="Squere Enix"/>
				<xs:enumeration value="Ubisoft"/>
				<xs:enumeration value="Valve"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="tekst">
		<xs:complexType>
			<xs:attribute name="rok" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:short">
						<xs:minInclusive value="2000"/>
						<xs:maxInclusive value="2050"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ulica">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_ulica">
					<xs:attribute name="nr" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="0"/>
								<xs:maxInclusive value="200"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="miasto">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="2"/>
				<xs:maxLength value="30"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="podpis">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="autor" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tytuł">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="telefon">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_telefon">
					<xs:attribute name="kier" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:pattern value="[0-9]{2}"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="twórcy">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="wydawcy">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="d" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dokument">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nagłówek"/>
				<xs:element ref="kolekcja"/>
				<xs:element ref="wydawcy"/>
			</xs:sequence>
		</xs:complexType>
		<xs:keyref name="idref" refer="wydId">
			<xs:selector xpath="kolekcja/ulubione/gra/dystrybutor"/>
			<xs:field xpath="@idref"/>
		</xs:keyref>
		<xs:key name="wydId">
			<xs:selector xpath=".//d"/>
			<xs:field xpath="@id"/>
		</xs:key>
	</xs:element>
	<xs:element name="kolekcja">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="zdjęcie"/>
				<xs:element ref="tekst"/>
				<xs:element ref="ulubione"/>
				<xs:element ref="zdjęcie"/>
				<xs:element ref="tekst"/>
				<xs:element ref="ulubione"/>
				<xs:element ref="zdjęcie"/>
				<xs:element ref="tekst"/>
				<xs:element ref="ulubione"/>
				<xs:element ref="zdjęcie"/>
				<xs:element ref="tekst"/>
				<xs:element ref="ulubione"/>
				<xs:element ref="zdjęcie"/>
				<xs:element ref="tekst"/>
				<xs:element ref="ulubione"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ulubione">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="gra" maxOccurs="unbounded"/>
				<xs:element ref="data"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="zdjęcie">
		<xs:complexType/>
	</xs:element>
	<xs:element name="nagłówek"/>
	<xs:element name="dystrybutor">
		<xs:complexType>
			<xs:attribute name="idref" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="kod_pocztowy">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[0-9][0-9][-][0-9][0-9][0-9]"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="data_premiery" type="xs:date"/>
	<xs:element name="rok_produkcji">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1980"/>
				<xs:maxInclusive value="2150"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="ST_cena">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0.10"/>
			<xs:maxExclusive value="399.99"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ST_ulica">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ST_telefon">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9][0-9][0-9][-][0-9][0-9][-][0-9][0-9]"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== mwprezes/XML/zadanie5 test.xml
<?xml version="1.0" encoding="UTF-8"?>
<dokument xmlns="http://www.example.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.com zadanie5.xsd">
  <nagłówek>
    <temat>
      <tematTematu>THE BEST GAME COLLECTION</tematTematu>
    </temat>
    <podpis>
      <autor>Mateusz Szejner</autor> &amp; <autor>Marcin Waligórski</autor></podpis>
    <cytat>
			"Hello, 47" <kto>Hitman</kto></cytat>
  </nagłówek>
  <kolekcja>
    <zdjęcie />
    <tekst rok="2018" />
    <ulubione>
      <gra id="p01" gatunek="Akcji">
        <tytuł>Party Cleansing</tytuł>
        <twórcy>NoRisk Studio</twórcy>
        <data_premiery>2018-01-31</data_premiery>
        <dystrybutor idref="d1" />
        <cena waluta="PLN">37.49</cena>
        <rok_produkcji>2017</rok_produkcji>
      </gra>
      <gra id="p08" gatunek="Turowa &amp; Tower defense">
        <tytuł>Rat-ujcie!</tytuł>
        <twórcy>NoFun Studio</twórcy>
        <data_premiery>2018-07-01</data_premiery>
        <dystrybutor idref="d1" />
        <cena waluta="PLN">33.99</cena>
        <rok_produkcji>2018</rok_produkcji>
      </gra>
      <data>PONIEDZIAŁEK 19 MARCA 2018 22:00</data>
      <gra id="ID" gatunek="Dev" xmlns="">
        <tytuł>Tytul</tytuł>
        <twórcy>Dev</twórcy>
        <data_premiery>Premiera</data_premiery>
        <dystrybutor idref="wydawca" />
        <cena waluta="PLN">Cena</cena>
        <rok_produkcji>Produkcja</rok_produkcji>
      </gra>
    </ulubione>
    <zdjęcie />
    <tekst rok="2017" />
    <ulubione>
      <gra id="p02" gatunek="Akcji">
        <tytuł>Wombat Combat</tytuł>
        <twórcy>NoRisk Studio</twórcy>
        <data_premiery>2017-01-31</data_premiery>
        <dystrybutor idref="d1" />
        <cena waluta="PLN">37.49</cena>
        <rok_produkcji>2017</rok_produkcji>
      </gra>
      <gra id="p07" gatunek="Symulator">
        <tytuł>Flight Simulator</tytuł>
        <twórcy>Microsoftware</twórcy>
        <data_premiery>2016-07-01</data_premiery>
        <dystrybutor idref="d2" />
        <cena waluta="PLN">39.99</cena>
        <rok_produkcji>2016</rok_produkcji>
      </gra>
      <gra id="p03" gatunek="Zombie &amp; coop">
        <tytuł>Left for Bread</tytuł>
        <twórcy>Valvo</twórcy>
        <data_premiery>2010-08-12</data_premiery>
        <dystrybutor idref="d4" />
        <cena waluta="PLN">19.99</cena>
        <rok_produkcji>2010</rok_produkcji>
      </gra>
      <gra id="p06" gatunek="Akcji &amp; Skradanka">
        <tytuł>Kredki Asasyna</tytuł>
        <twórcy>UBI</twórcy>
        <data_premiery>2008-08-08</data_premiery>
        <dystrybutor idref="d2" />
        <cena waluta="PLN">29.99</cena>
        <rok_produkcji>2008</rok_produkcji>
      </gra>
      <gra id="p04" gatunek="Akcji &amp; Skradanka">
        <tytuł>Hitman</tytuł>
        <twórcy>IO</twórcy>
        <data_premiery>2017-07-07</data_premiery>
        <dystrybutor idref="d5" />
        <cena waluta="EUR">59.99</cena>
        <rok_produkcji>2017</rok_produkcji>
      </gra>
      <gra id="p05" gatunek="Strategia &amp; RTS">
        <tytuł>Serca z Żelaza</tytuł>
        <twórcy>Paradoxal</twórcy>
        <data_premiery>2016-06-06</data_premiery>
        <dystrybutor idref="d5" />
        <cena waluta="PLN">99.99</cena>
        <rok_produkcji>2016</rok_produkcji>
      </gra>
      <data>ŚRODA 20 GRUDNIA 2017 23:34</data>
    </ulubione>
    <zdjęcie />
    <tekst rok="2016" />
    <ulubione>
      <gra id="p09" gatunek="Akcji">
        <tytuł>Black Spirits</tytuł>
        <twórcy>To Software</twórcy>
        <data_premiery>2016-04-24</data_premiery>
        <dystrybutor idref="d5" />
        <cena waluta="PLN">45.99</cena>
        <rok_produkcji>2015</rok_produkcji>
      </gra>
      <gra id="p10" gatunek="Akcji &amp; Strzelanka &amp; FPS &amp; Fabuła">
        <tytuł>Full-Life 2: Episode 2.5</tytuł>
        <twórcy>Valvo</twórcy>
        <data_premiery>2012-12-10</data_premiery>
        <dystrybutor idref="d4" />
        <cena waluta="PLN">69.99</cena>
        <rok_produkcji>2012</rok_produkcji>
      </gra>
      <gra id="p11" gatunek="Akcji &amp; Strzelanka &amp; FPS">
        <tytuł>Counter Offensive: Global Strike</tytuł>
        <twórcy>Valvo</twórcy>
        <data_premiery>2004-08-30</data_premiery>
        <dystrybutor idref="d4" />
        <cena waluta="PLN">41.99</cena>
        <rok_produkcji>2004</rok_produkcji>
      </gra>
      <gra id="p16" gatunek="Platformówka &amp; 3D">
        <tytuł>A Hat on a Timeline</tytuł>
        <twórcy>Gears for Lunch</twórcy>
        <data_premiery>2016-09-04</data_premiery>
        <dystrybutor idref="d1" />
        <cena waluta="PLN">29.99</cena>
        <rok_produkcji>2016</rok_produkcji>
      </gra>
      <gra id="p12" gatunek="Akcji &amp; Hack'n'Slash">
        <tytuł>RWBY: Grim Eclipse</tytuł>
        <twórcy>RT</twórcy>
        <data_premiery>2016-08-30</data_premiery>
        <dystrybutor idref="d3" />
        <cena waluta="PLN">39.99</cena>
        <rok_produkcji>2016</rok_produkcji>
      </gra>
      <data>CZWARTEK 17 LISTOPADA 2016 13:13</data>
    </ulubione>
    <zdjęcie />
    <tekst rok="2015" />
    <ulubione>
      <gra id="p13" gatunek="Strzelanka &amp; FPS &amp; Fabuła">
        <tytuł>Massive Effect</tytuł>
        <twórcy>Bio-Ware</twórcy>
        <data_premiery>2012-10-26</data_premiery>
        <dystrybutor idref="d3" />
        <cena waluta="PLN">129.99</cena>
        <rok_produkcji>2012</rok_produkcji>
      </gra>
      <gra id="p14" gatunek="Strzelanka &amp; FPS &amp; Fabuła">
        <tytuł>ShockingBio: Unlimited</tytuł>
        <twórcy>1K Inteactive</twórcy>
        <data_premiery>2014-11-16</data_premiery>
        <dystrybutor idref="d5" />
        <cena waluta="PLN">89.99</cena>
        <rok_produkcji>2014</rok_produkcji>
      </gra>
      <gra id="p15" gatunek="Przygodowa &amp; RPG &amp; Fabuła">
        <tytuł>Wiesiek</tytuł>
        <twórcy>CDPR</twórcy>
        <data_premiery>2015-12-20</data_premiery>
        <dystrybutor idref="d1" />
        <cena waluta="PLN">99.99</cena>
        <rok_produkcji>2015</rok_produkcji>
      </gra>
      <gra id="p17" gatunek="Strzelanka &amp; FPS">
        <tytuł>SuperCold</tytuł>
        <twórcy>ColdTeam</twórcy>
        <data_premiery>2015-09-18</data_premiery>
        <dystrybutor idref="d1" />
        <cena waluta="PLN">59.99</cena>
        <rok_produkcji>2015</rok_produkcji>
      </gra>
      <gra id="p18" gatunek="Przygodowa &amp; RPG &amp; Fabuła">
        <tytuł>Gothic IV</tytuł>
        <twórcy>SharkBytes</twórcy>
        <data_premiery>2013-08-20</data_premiery>
        <dystrybutor idref="d3" />
        <cena waluta="PLN">129.99</cena>
        <rok_produkcji>2013</rok_produkcji>
      </gra>
      <data>SOBOTA 29 GRUDNIA 2015 00:01</data>
    </ulubione>
    <zdjęcie />
    <tekst rok="2014" />
    <ulubione>
      <gra id="p19" gatunek="Symulacja &amp; Logiczna">
        <tytuł>Kernel Space Program</tytuł>
        <twórcy>Team</twórcy>
        <data_premiery>2014-11-20</data_premiery>
        <dystrybutor idref="d5" />
        <cena waluta="PLN">59.99</cena>
        <rok_produkcji>2014</rok_produkcji>
      </gra>
      <gra id="p20" gatunek="Strategia &amp; RTS">
        <tytuł>Space Wars: Empire at War</tytuł>
        <twórcy>PortoGlyph</twórcy>
        <data_premiery>2006-02-16</data_premiery>
        <dystrybutor idref="d2" />
        <cena waluta="PLN">19.99</cena>
        <rok_produkcji>2006</rok_produkcji>
      </gra>
      <gra id="p21" gatunek="Przygodowa &amp; JRPG">
        <tytuł>CoolDimension Neptune</tytuł>
        <twórcy>CompileOrgan</twórcy>
        <data_premiery>2010-09-19</data_premiery>
        <dystrybutor idref="d5" />
        <cena waluta="PLN">69.99</cena>
        <rok_produkcji>2010</rok_produkcji>
      </gra>
      <gra id="p22" gatunek="Przygodowa &amp; RPG">
        <tytuł>The Old Texts: Sky-Rim</tytuł>
        <twórcy>TODD</twórcy>
        <data_premiery>2011-11-11</data_premiery>
        <dystrybutor idref="d3" />
        <cena waluta="EUR">69.99</cena>
        <rok_produkcji>2011</rok_produkcji>
      </gra>
      <data>SOBOTA 29 LISTOPADA 2014 22:20</data>
    </ulubione>
  </kolekcja>
  <wydawcy>
    <d id="d1">
      <nazwa>CD Projekt</nazwa>
      <miasto>Warszawa</miasto>
      <ulica nr="91">Łódzka</ulica>
      <kod_pocztowy>05-850</kod_pocztowy>
      <telefon kier="22">733-51-50</telefon>
    </d>
    <d id="d2">
      <nazwa>Ubisoft</nazwa>
      <miasto>Montreal</miasto>
      <ulica nr="21">Kanadyjska</ulica>
      <kod_pocztowy>15-650</kod_pocztowy>
      <telefon kier="15">548-35-50</telefon>
    </d>
    <d id="d3">
      <nazwa>EA</nazwa>
      <miasto>Hell</miasto>
      <ulica nr="41">Hopeless</ulica>
      <kod_pocztowy>30-666</kod_pocztowy>
      <telefon kier="51">665-52-45</telefon>
    </d>
    <d id="d4">
      <nazwa>Valve</nazwa>
      <miasto>Waszyngton</miasto>
      <ulica nr="53">Bellevue</ulica>
      <kod_pocztowy>87-598</kod_pocztowy>
      <telefon kier="22">245-87-77</telefon>
    </d>
    <d id="d5">
      <nazwa>Squere Enix</nazwa>
      <miasto>Nowy York</miasto>
      <ulica nr="67">Parkowa</ulica>
      <kod_pocztowy>10-894</kod_pocztowy>
      <telefon kier="54">168-58-47</telefon>
    </d>
  </wydawcy>
</dokument>
